### ISSUE TITLE
"A new code requires a code file." issue

### ISSUE THREAD

**Issue by cluppi** [iron-io/laraworker#5]
While trying to upload a worker, I'm seeing the error below:

  [Http_Exception]
  http error: 400 | {"msg":"A new code requires a code file."}

**Comment by cluppi** [comment]
Narrowed it down to this issue:

http://stackoverflow.com/questions/25934128/curl-file-uploads-not-working-anymore-after-upgrade-from-php-5-5-to-5-6

I tried setting curl_setopt($this->curl, CURLOPT_SAFE_UPLOAD, false);  and it fixed the issue.

**Comment by alnutile** [comment]
@cluppi is this where the fix had to go https://github.com/iron-io/iron_core_php/blob/master/src/IronCore.php#L269 ?
