### ISSUE TITLE
Composer error with Laravel 4.2

### ISSUE THREAD

**Issue by kevinduellman** [iron-io/laraworker#9]
When following instructions for installation, my local Laravel app throws an error saying file_get_contents(composer.json) file ../iron-io/laraworker/LaraWorker.php not found. The file does in fact exist, but the error prevents routes from being executed. 

The only way I have found to resolve the issue is commenting out the line: 

$vendorDir . '/iron-io/laraworker/LaraWorker.php',

in autoload_files.php, which is obviously not ideal. 

Since there is not tag, I am installing via composer using "dev-master".

**Comment by gg67** [comment]
Getting the same issue in Laravel 5.1

Update:

Seems to be a php version thing. Upgrading to php 5.6 seems to fix it.

**Comment by mjmgooch** [comment]
Getting the same issue on Laravel 4.2

Perhaps an alternative to commenting out the line @kduellman suggests is to open LaraWorker.php and altering the get_laravel_version() function to simply return your version of laravel:

```
function get_laravel_version()
{
    //$composer_content = file_get_contents('composer.json');
    //$content_arr = json_decode($composer_content, true);
    //$version_arr = $content_arr["require"]["laravel/framework"];
    return '4.2';
}
```

Not ideal but its still included in your autoload this way,

**Comment by kevinduellman** [comment]
@mjmgooch has better solution, don't have to keep going back to comment out that line on every composer update...

@gg67 on Laravel 4.2, php 5.6, issue has not gone away for me...
